#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

# boot picom
if [ -x "$(command -v picom)" ]; then
  picom --config ${SCRIPTPATH}/picom/picom.conf &> /dev/null &
fi

# load theme.ron
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize $SCRIPTPATH/wallpapers/
fi

# boot polybar for each monitor
if [ -x "$(command -v polybar)" ]; then
    polybar -m | sed s/:.*// | while read -r monitor; do
        monitor=$monitor polybar -c ${SCRIPTPATH}/polybar/config.ini main &> /tmp/polybar.log &
    done
fi
